### PR TITLE
feat: expose tar-path parameter

### PR DESCRIPTION
**Pull request by earwik**
This is useful for testing, but we also have use cases where we don't need to push the built image but will use it in another build stage.

### CODE REVIEW

**Review by plyr4 — APPROVED** [review]
awesome, thanks @earwik

**Comment by wass3rw3rk** [comment]
good once conflicts are resolved - thank you

**Review by wass3r — CHANGES_REQUESTED** [review]
sorry to be a pain, but can we drop the upgrade to urfave/cli lib from this PR? i don't believe it's needed here.

**Comment by earwik** [comment]
> sorry to be a pain, but can we drop the upgrade to urfave/cli lib from this PR? i don't believe it's needed here.

Done, sorry didn't intend that anyhow

**Review by wass3rw3rk — APPROVED** [review]
lgtm - thanks!

**Review by plyr4 — APPROVED** [review]

**Review by wass3r — APPROVED** [review]

**Pull request merged**
